### ISSUE TITLE
Adding Search Forms

### ISSUE THREAD

**Issue by q3799** [qualitykiosk/qeeper#9]
Need to add search forms in multiple places. Later on, will break this ticket into multiple.

**Comment by q5189** [comment]
Closing this ticket as multiple tickets for each entity page is created to add Search form.
ticket numbers are as follows : 
#12 Adding Search Form at Bank Accounts Page
#13 Adding Search Form at Banks Page
#14 Adding Search Form at Contact People Page
#15 Adding Search Form at Escalation Matrices Page
#16 Adding Search Form at Bank Branches Page
#17 Adding Search Form at Mobile Numbers Page
#18 Adding Search Form at Employees Page
#19 Adding Search Form at Cards Page
#20 Adding Search Form at Mail Logs Page
#21 Adding Search Form at SMS Logs Page
